name: Deploy FastAPI to EC2

# üîπ Manual trigger only
on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.ECR_REPO_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1Ô∏è‚É£ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4


      # 2Ô∏è‚É£ Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # 3Ô∏è‚É£ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      # 4Ô∏è‚É£ Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .


      # 5Ô∏è‚É£ Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag $IMAGE_NAME:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:latest


      # 6Ô∏è‚É£ Push Docker Image to ECR
      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:latest


      # 7Ô∏è‚É£ Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Login to ECR from EC2 (IAM Role must be attached)
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            # Pull latest image
            docker pull \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:latest

            # Stop old container if exists
            docker stop fraud-api || true
            docker rm fraud-api || true

            # Run new container
            docker run -d \
              -p 8000:8000 \
              --name fraud-api \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:latest
