name: Deploy FastAPI to EC2

# üîπ Manual Trigger Only
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}

    steps:

      # ==========================
      # 1Ô∏è‚É£ Checkout Repository
      # ==========================
      - name: Checkout Code
        uses: actions/checkout@v4


      # ==========================
      # 2Ô∏è‚É£ Configure AWS Credentials
      # ==========================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # ==========================
      # 3Ô∏è‚É£ Login to Amazon ECR
      # ==========================
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      # ==========================
      # 4Ô∏è‚É£ Build Docker Image
      # ==========================
      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPO_NAME .


      # ==========================
      # 5Ô∏è‚É£ Tag Docker Image
      # ==========================
      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPO_NAME:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest


      # ==========================
      # 6Ô∏è‚É£ Push Docker Image
      # ==========================
      - name: Push Docker Image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest


      # ==========================
      # 7Ô∏è‚É£ Deploy to EC2
      # ==========================
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO_NAME }}

            echo "Logging into ECR..."
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            echo "Pulling latest image..."
            docker pull $ECR_URI:latest

            echo "Stopping old container (if exists)..."
            docker stop fraud-api || true
            docker rm fraud-api || true

            echo "Starting new container..."

            docker run -d \
              -p 8000:8000 \
              --name fraud-api \
              --restart always \
              -e MLFLOW_TRACKING_URI='${{ secrets.MLFLOW_TRACKING_URI }}' \
              -e MLFLOW_TRACKING_USERNAME='${{ secrets.MLFLOW_TRACKING_USERNAME }}' \
              -e MLFLOW_TRACKING_PASSWORD='${{ secrets.MLFLOW_TRACKING_PASSWORD }}' \
              $ECR_URI:latest

            echo "Deployment completed successfully."
