name: ML Training CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  training-ci:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install "dvc[http]"

      # 1️⃣ Code Quality Check
      - name: Code Quality Check
        run: |
          flake8 src/

      # 2️⃣ Unit Tests
      - name: Run Unit Tests
        run: |
          pytest tests/

      # Configure DVC
      - name: Configure DVC Remote
        run: |
          dvc remote modify origin auth basic
          dvc remote modify origin user $DAGSHUB_USERNAME
          dvc remote modify origin password $DAGSHUB_TOKEN

      - name: DVC Pull
        run: |
          dvc pull

      - name: Run DVC Pipeline
        run: |
          dvc repro

      # 3️⃣ Model Performance Gate
      - name: Model Performance Gate
        run: |
          python scripts/model_performance_gate.py
